apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.fxpInitialConfigMapName }}
  namespace: {{ default .Release.Namespace (index .Values "mojaloop-fxp" "namespace") }}
  labels:
    app: {{ template "casa.name" . }}
    chart: {{ template "casa.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  fxpInitialConfiguration.json: {{ .Files.Get .Values.fxpInitialConfigFile | quote }}
