apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.fspVerificationCertsSecretName }}
  namespace: {{ default .Release.Namespace (index .Values "mojaloop-fxp" "namespace") }}
  labels:
    app: {{ template "casa.name" . }}
    chart: {{ template "casa.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- (.Files.Glob .Values.fspVerificationCertsGlob).AsSecrets | nindent 2 }}
