apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-volume
  # The label is used for matching the exact claim
  labels:
    usage: kafka-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    # Replace with your secret name
    secretName: volume-azurefile-storage-secret
    # Replace with correct storage share name
    shareName: uatstacc
    # In case the secret is stored in a different namespace
    #secretNamespace: default
    readOnly: false