apiVersion: v1
kind: Secret
metadata:
  name: volume-azurefile-storage-secret
type: Opaque
data:
  azurestorageaccountname: dWF0c3RhY2M=
  azurestorageaccountkey: OUVaYUs3NlFwRDZiang0OGlKUHlOd3haWTZub0NWUkRxeUJiTEdPakx0WXNaaG1TWkhaOUltQUJ5YWhyd1B3WmJmZFIvTEpLclVpbEtNd3NUM1Y5cGc9PQ==